
[composite]
documentation = """
C <- gemm(1.0, A, B, C, 0.0)
"""

name = "Gemm"
inputs = ["A{float}[M K]<0 1>()", "B{float}[K N]<0 1>()", "C{float}[M N]<0 1>()"]
outputs = ["C"]

[implementation]
code = """
(dotimes (i m)
  (dotimes (j n)
    (dotimes (p k)
      (incf (aref C i j) (* (aref A i p) (aref B p j))))))
"""

[test]
requirements = [""]
code = """
(lambda (A B C k m n)
  (dotimes (i m)
    (dotimes (j n)
      (dotimes (p k)
        (incf (aref C i j) (* (aref A i p) (aref B p j)))))))
"""
