[composite]
documentation = """
Multiplies two matrices.
"""
name = "Gemm"
inputs = ["A{T}[i j]<1 0>()", "B{T}[j k]<1 0>()", "C{T}[i k]<1 0>()"]
outputs = ["C"]

[implementation]
code = """
(dotimes (i1 i)
    (dotimes (j1 i)
        (dotimes (k1 i)
	    (incf (aref c i1 k1) (* (aref a i1 j1) (aref b j1 k1))))))
"""
