[composite]
documentation = """
Sin
"""
name = "Sin"
inputs = ["A{Float}[N]<0>()", "B{Float}[N]<0>()"]
outputs = ["B"]

[implementation]
code = """
(dotimes (i N)
    (setf (aref B i) (sin (aref A i))))
"""
